### ISSUE TITLE
Reads in real number as an integer and a float

### ISSUE THREAD

**Issue by GarrettLimon1** [MDAnalysis/GridDataFormats#3] opened 2015-05-22 22:41 UTC
Using gridDataFormats I wrote out a grid in a .dx file and also read it back into my program. Upon loading in the file, one number on my grid, -9e-0.5, was being read in as an integer -9 and a string 'e-05'. My advisor and I made a quick fix for now, but we wanted you to be aware of the issue. It is in [line 426 of OpenDX.py](https://github.com/MDAnalysis/GridDataFormats/blob/master/gridData/OpenDX.py#L426). I would attach a copy of the file that raised the issue, but its format is not supported on here.

**Comment by orbeckst** [comment] 2015-06-29 22:42
Thanks, do you want to contribute your fix?

**Comment by orbeckst** [comment] 2015-06-29 22:49
@GarrettLimon1 , are you sure that `-9e-0.5` is a legal scientific notation number, with the exponent a fraction?? The regular expression starting at [line 417](https://github.com/MDAnalysis/GridDataFormats/blob/master/gridData/OpenDX.py#L417) will not recognize `-9e-0.5` as a number. Can you provide a reference that exponents can be fractional?

Btw, I linked your line number to the code for quick lookup.

**Comment by orbeckst** [comment] 2015-06-29 22:56
In Python, the exponent *must be integer*
```python
In [2]: 3e4.4
  File "<ipython-input-2-c625c5342b57>", line 1
    3e4.4
        ^
SyntaxError: invalid syntax
```
and at least the [Wikipedia page on Scientific Notation](https://en.wikipedia.org/wiki/Scientific_notation) also states that the exponent is an integer.

I am inclined to close this issue in a week without further action unless you provide a reason why this ought to be fixed.

**Comment by GarrettLimon1** [comment] 2015-06-29 23:45
Sorry, typo. You're right, that is not a number, but the number in question was -9e-05. Also, the number itself was generated by python. We believe that the reason for the issue is that the '-9' was at the end of its line and the 'e-0.5' was at the beginning of the following line. It may have just been flook with the grid that I created, but we wanted to point it out.

**Comment by orbeckst** [comment] 2015-06-29 23:59
You're right, something like
```
1.2e00 4.56e-08 -9
e-05  -3.45e-02
```
will not be matched. Is this common or even legal in a DX file?

**Comment by GarrettLimon1** [comment] 2015-06-30 06:21
Well like I said before, Python generated my grid and the numbers in it. I just used a simple 3D hat function to do so. Then I wrote the grid out into the dx file using gridData, which was done no problem. The problem was then reading it back in using gridData. I don't know why -9e-05 wouldn't be legal in a DX file, but if you mean the placement of it being at the end of the line, that was done by gridData when it output the file. As for that occurrence being common, I'm not sure because of my limited experience with .dx files, but I would think not. I will bring it up tomorrow to my advisor and see what he thinks about it.

**Comment by orbeckst** [comment] 2015-06-30 07:09
If gridData wrote it then file it as a new bug because then the problem really is that gridData is writing in a bad format (i.e. breaking numbers across lines).

If you can provide example code that reproduces the problem then that would be extremely helpful.

Thanks,
Oliver

On 29 Jun, 2015, at 23:21, GarrettLimon1 wrote:

> Well like I said before, Python generated my grid and the numbers in it. I just used a simple 3D hat function to do so. Then I wrote the grid out into the dx file using gridData, which was done no problem. The problem was then reading it back in using gridData. I don't know why -9e-05 wouldn't be legal in a DX file, but if you mean the placement of it being at the end of the line, that was done by gridData when it output the file. As for that occurrence being common, I'm not sure because of my limited experience with .dx files, but I would think not. I will bring it up tomorrow to my advisor and see what he thinks about it.

--
Oliver Beckstein * orbeckst@gmx.net
skype: orbeckst  * orbeckst@gmail.com

**Comment by GarrettLimon1** [comment] 2015-06-30 17:01
I saved and gzipped the problem .dx file that was created, but upon unzipping it I realized that the numbers are now together on the line, so I don't think that gridData will have trouble reading it in anymore. 

Unfortunately I've also changed a lot inside of my program since and I'm not sure the exact parameters that output that file. I will try to recreate it but right now I don't have the code. I do remember that it was a gaussian density distribution that was being created, if that helps. 

If I can recreate the problem again I will send you the code ASAP.

**Comment by orbeckst** [comment] 2015-08-06 17:44
I decided that numbers broken across line is an illegal DX format and the *reader* will not support it.

I don't have sufficient data to see if the problem is GridDataFormat writing a DX file with numbers broken across lines (which was the original problem). I am now closing the issue. If it turns out that *writing* is a problem, please open a new issue specifically for this problem (and reference #3).

**Closed by orbeckst** 2015-08-06 17:44 UTC
Labels: wrong results
